### ISSUE TITLE
Find better name for the project.

### ISSUE THREAD

**Issue by marehr** [eaasna/valik#24]

**Comment by eaasna** [comment]
Ideas:
- stellar_prefilter, local_prefilter
    - straight-forward but kind of long
-  FILS (pre-**FI**lter for **L**ocal sequence **S**imilarity search)
    - similar to how they named DREAM-Yara, Lambda etc
-  valik
    - this one means "filter/selection" in Estonian but should still be easy to spell/pronounce for anyone

**Comment by marehr** [comment]
I like the idea of the Estonian one, but I also like the really obvious ones.

stellar_prefilter might be too specific, as the method itself is more general for local alignments. On the other hand we could also optimize the use case for stellar if we name it as such.

Maybe tähe-valik xD
